In [1]:
import scipy.io as sio
import numpy as np

In [2]:
from scipy.io import arff

In [3]:
data = arff.loadarff('iris.arff')

In [4]:
A = np.array(data);
A = np.array(data[0]);


In [5]:
def make_array(a):
    L = []
    for i in range(150): 
        L.append(list(a[i]))
    return L



In [6]:
def make_type_array(a):
    C = []
    for i in range(len(a)):
        C.append(a[i][4])
        del(a[i][4])
    return C

In [7]:
Ar = make_array(A);
Dr = make_type_array(Ar);


In [8]:
X = np.array(Ar);
T_array = np.array(Dr)

In [9]:
from collections import Counter

In [10]:
fre = Counter(T_array);
T_array = list(range(len(fre)));
T_array

[0, 1, 2]

Teraz w numpy array X są dane liczbowe, w T_array są kolejne liczby dla typów (trzech w tym przypadku). Funkcje manipulują tablicami, żeby uzyskać zgodnośc z warunkami zadania, a z typów, zgodnie z punktem dwa jest tworzona tablica liczb przy pomocy Countera z collections (daje częstości występowania elementów - fre), a potem tylko wystarczy zrobić z ich długości listę : T_array = list(range(len(fre)))


In [11]:
# Przykładowa tablica do szukania 90%:
values_list = [1.7, 0.7, 3.4, 0.2]
def find_ninety_percent(a):
    a = np.sort(a)
    a = a[::-1]
    print("a po sortowaniu", a)
    sorted_indexes = np.argsort(a)
    sorted_indexes = sorted_indexes[::-1]
    sum_list = (np.sum(a) * 90) / 100
    s = a[0]
    cnt = 1
    for x in a[1:]:
        if s < sum_list:
            s += x
            cnt += 1
        elif s >= sum_list:
            return [s, sorted_indexes[:cnt]]
    str1 = "Values could not be added up to 90% sum"
    return str1
            
    

In [12]:
#Po kolei :
#linia 4 i 5 posortowanie tablicy (od najmniejszej więc tzreba odwrócić);    
#to samo z indeksami z argsortu     
#linia 9: obliczenie 90%    
#linie 90, 10 - ustalenie chwilowej sumy - na pierwszy element, i licznika na 1 (zaczynamy oid drugiego elementu)    
#linie od 12 do 17 iteracja, zwiekszanie sumy i licznika, gdy jest mnijsza od 90%      
#linia 17 zwracamy wynik (gdy jest): sume n wartości własnych potzrebnych do uzyskania 90% oraz listę ich indeksów po posortowaniu i odwróceniu

In [13]:
find_ninety_percent(values_list)

a po sortowaniu [ 3.4  1.7  0.7  0.2]


[5.7999999999999998, array([0, 1, 2])]

In [14]:
a = [2, 3, 1];
import operator as op

In [15]:
sorted(a, reverse=True)

[3, 2, 1]

In [16]:
# Macierz kowariancji:
cov_mat = np.cov(np.transpose(X));
cov_mat

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [21]:
# Wartości własne i wektory własne macierzy cov:
eigen_val, eigen_vec = np.linalg.eig(cov_mat);
eigen_val, eigen_vec;

a po sortowaniu [ 4.22484077  0.24224357  0.07852391  0.02368303]


[4.224840768320111, array([0])]

In [35]:
# kolumna 0 i 1 z eig_vec to wektory własne odpowiadające wartościom 0 i 1, tu: 4.2248... i 0.2422435:
c1 = eigen_vec[:, 0];
c2 = eigen_vec[:, 1];


In [37]:
# Macierz z wybranych eigen_vec:
V = np.array([c1, c2]);
V.T # Transponowana

array([[ 0.36158968, -0.65653988],
       [-0.08226889, -0.72971237],
       [ 0.85657211,  0.1757674 ],
       [ 0.35884393,  0.07470647]])

In [28]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [38]:
# Rzut, jak podaje Wikipedia
np.matmul(X, V.T) 
# tu musisz sobie powybierać różne wartości własne i popatrzeć jak to sie transformuje


array([[ 2.82713597, -5.64133105],
       [ 2.79595248, -5.14516688],
       [ 2.62152356, -5.17737812],
       [ 2.7649059 , -5.00359942],
       [ 2.78275012, -5.64864829],
       [ 3.23144574, -6.06250644],
       [ 2.69045242, -5.23261922],
       [ 2.8848611 , -5.48512908],
       [ 2.62338453, -4.7439257 ],
       [ 2.83749841, -5.20803203],
       [ 3.00481631, -5.96665874],
       [ 2.89820038, -5.33624436],
       [ 2.72390912, -5.08698354],
       [ 2.28614265, -4.81144382],
       [ 2.86779988, -6.50091863],
       [ 3.12747377, -6.65947808],
       [ 2.88881689, -6.13281341],
       [ 2.86302037, -5.6338604 ],
       [ 3.31226514, -6.19396782],
       [ 2.92399691, -5.83519737],
       [ 3.2008114 , -5.71259155],
       [ 2.96810819, -5.75475549],
       [ 2.2954854 , -5.4563393 ],
       [ 3.20821456, -5.42024641],
       [ 3.15517201, -5.28351414],
       [ 3.00342587, -5.17566739],
       [ 3.0422871 , -5.45261105],
       [ 2.94895215, -5.68940829],
       [ 2.87152183,